name: personal_site
description: A new Flutter application.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_background: ^1.0.5
  animated_size_and_fade: ^1.1.3
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
        - asset: assets/fonts/Inconsolata-Medium.ttf
        - asset: assets/fonts/Inconsolata-SemiBold.ttf
        - asset: assets/fonts/Inconsolata-Bold.ttf

